# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7da7512c71e91cc5f5d3a68cc2a18973be34f04513b1dca55adee832fe8f2d2fd47a01657f70902bdae84555406f3ff3b51d50750a42cb4532fa08f80ecc97e

test:
  secret_key_base: 1f3bb97c555f19dad99484907ba23b6fb12103c1fe99252f369074655ca90dffb0f5cfd680126c951fb04e50e7ee3bae012badea96f3881eec7d448a03531abb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
